export type LandmarkType =
  | "clockTower"
  | "tower"
  | "gate"
  | "dome"
  | "library"
  | "chapel"
  | "hall"
  | "arch"
  | "statue"
  | "tree"
  | "well"
  | "rotunda"
  | "stadium";

export type SchoolMarkStyle =
  | "serif"
  | "block"
  | "shield"
  | "round"
  | "minimal";

export type SchoolTexture =
  | "none"
  | "grid"
  | "arches"
  | "rays"
  | "dots"
  | "ivy";

export type SchoolIdentity = {
  id: string;
  name: string;
  shortName: string;
  aliases: string[];
  city: string;
  markText: string;
  markStyle: SchoolMarkStyle;
  landmark: string;
  landmarkType: LandmarkType;
  primary: string;
  secondary: string;
  highlight: string;
  texture: SchoolTexture;
  officialLogoSrc?: string | null;
};

const identities: SchoolIdentity[] = [
  {
    id: "vanderbilt",
    name: "Vanderbilt University",
    shortName: "Vanderbilt",
    aliases: ["vanderbilt", "vanderbilt university", "vu"],
    city: "Nashville",
    markText: "V",
    markStyle: "serif",
    landmark: "Kirkland Hall",
    landmarkType: "clockTower",
    primary: "#CFAE70",
    secondary: "#1C1C1C",
    highlight: "#F3DFB6",
    texture: "rays",
  },
  {
    id: "michigan",
    name: "University of Michigan",
    shortName: "Michigan",
    aliases: [
      "university of michigan",
      "university of michigan-ann arbor",
      "michigan",
      "umich",
      "u-m",
    ],
    city: "Ann Arbor",
    markText: "M",
    markStyle: "block",
    landmark: "Burton Memorial Tower",
    landmarkType: "clockTower",
    primary: "#FFCB05",
    secondary: "#00274C",
    highlight: "#FFE766",
    texture: "grid",
  },
  {
    id: "illinois",
    name: "University of Illinois Urbana-Champaign",
    shortName: "Illinois",
    aliases: [
      "university of illinois urbana-champaign",
      "university of illinois at urbana-champaign",
      "uiuc",
      "illinois",
    ],
    city: "Champaign-Urbana",
    markText: "I",
    markStyle: "block",
    landmark: "Alma Mater",
    landmarkType: "statue",
    primary: "#FF5F05",
    secondary: "#13294B",
    highlight: "#FF8A3D",
    texture: "grid",
  },
  {
    id: "indiana",
    name: "Indiana University Bloomington",
    shortName: "Indiana",
    aliases: [
      "indiana university",
      "indiana university bloomington",
      "iu",
      "indiana",
    ],
    city: "Bloomington",
    markText: "IU",
    markStyle: "serif",
    landmark: "Sample Gates",
    landmarkType: "gate",
    primary: "#990000",
    secondary: "#EEEDEB",
    highlight: "#CC3333",
    texture: "arches",
  },
  {
    id: "northwestern",
    name: "Northwestern University",
    shortName: "Northwestern",
    aliases: ["northwestern university", "northwestern", "nu"],
    city: "Evanston",
    markText: "N",
    markStyle: "serif",
    landmark: "Weber Arch",
    landmarkType: "arch",
    primary: "#4E2A84",
    secondary: "#FFFFFF",
    highlight: "#836EAA",
    texture: "arches",
  },
  {
    id: "notre-dame",
    name: "University of Notre Dame",
    shortName: "Notre Dame",
    aliases: ["university of notre dame", "notre dame", "nd"],
    city: "Notre Dame",
    markText: "ND",
    markStyle: "serif",
    landmark: "Golden Dome",
    landmarkType: "dome",
    primary: "#C99700",
    secondary: "#0C2340",
    highlight: "#E8C55A",
    texture: "rays",
  },
  {
    id: "purdue",
    name: "Purdue University",
    shortName: "Purdue",
    aliases: ["purdue university", "purdue"],
    city: "West Lafayette",
    markText: "P",
    markStyle: "block",
    landmark: "Purdue Bell Tower",
    landmarkType: "tower",
    primary: "#CFB991",
    secondary: "#000000",
    highlight: "#E8D6B0",
    texture: "grid",
  },
  {
    id: "wisconsin",
    name: "University of Wisconsin-Madison",
    shortName: "Wisconsin",
    aliases: [
      "university of wisconsin-madison",
      "university of wisconsin madison",
      "uw-madison",
      "wisconsin",
    ],
    city: "Madison",
    markText: "W",
    markStyle: "block",
    landmark: "Bascom Hall",
    landmarkType: "hall",
    primary: "#C5050C",
    secondary: "#FFFFFF",
    highlight: "#E45B60",
    texture: "grid",
  },
  {
    id: "ohio-state",
    name: "The Ohio State University",
    shortName: "Ohio State",
    aliases: [
      "the ohio state university",
      "ohio state university",
      "ohio state",
      "osu",
    ],
    city: "Columbus",
    markText: "O",
    markStyle: "round",
    landmark: "Orton Hall",
    landmarkType: "clockTower",
    primary: "#BB0000",
    secondary: "#666666",
    highlight: "#E05252",
    texture: "grid",
  },
  {
    id: "penn-state",
    name: "Pennsylvania State University",
    shortName: "Penn State",
    aliases: [
      "pennsylvania state university",
      "penn state university",
      "penn state",
      "psu",
    ],
    city: "University Park",
    markText: "PS",
    markStyle: "shield",
    landmark: "Old Main",
    landmarkType: "hall",
    primary: "#001E44",
    secondary: "#FFFFFF",
    highlight: "#3D5C83",
    texture: "grid",
  },
  {
    id: "harvard",
    name: "Harvard University",
    shortName: "Harvard",
    aliases: ["harvard university", "harvard"],
    city: "Cambridge",
    markText: "H",
    markStyle: "shield",
    landmark: "Widener Library",
    landmarkType: "library",
    primary: "#A51C30",
    secondary: "#000000",
    highlight: "#D95B6D",
    texture: "ivy",
  },
  {
    id: "yale",
    name: "Yale University",
    shortName: "Yale",
    aliases: ["yale university", "yale"],
    city: "New Haven",
    markText: "Y",
    markStyle: "serif",
    landmark: "Harkness Tower",
    landmarkType: "tower",
    primary: "#00356B",
    secondary: "#FFFFFF",
    highlight: "#4E79A7",
    texture: "ivy",
  },
  {
    id: "princeton",
    name: "Princeton University",
    shortName: "Princeton",
    aliases: ["princeton university", "princeton"],
    city: "Princeton",
    markText: "P",
    markStyle: "shield",
    landmark: "Nassau Hall",
    landmarkType: "hall",
    primary: "#E77500",
    secondary: "#000000",
    highlight: "#F4A34C",
    texture: "ivy",
  },
  {
    id: "columbia",
    name: "Columbia University",
    shortName: "Columbia",
    aliases: ["columbia university", "columbia"],
    city: "New York",
    markText: "C",
    markStyle: "serif",
    landmark: "Low Memorial Library",
    landmarkType: "dome",
    primary: "#B9D9EB",
    secondary: "#003865",
    highlight: "#E3F2F9",
    texture: "grid",
  },
  {
    id: "penn",
    name: "University of Pennsylvania",
    shortName: "Penn",
    aliases: [
      "university of pennsylvania",
      "penn",
      "upenn",
    ],
    city: "Philadelphia",
    markText: "P",
    markStyle: "shield",
    landmark: "College Hall",
    landmarkType: "hall",
    primary: "#011F5B",
    secondary: "#990000",
    highlight: "#4D6C9F",
    texture: "ivy",
  },
  {
    id: "cornell",
    name: "Cornell University",
    shortName: "Cornell",
    aliases: ["cornell university", "cornell"],
    city: "Ithaca",
    markText: "C",
    markStyle: "serif",
    landmark: "McGraw Tower",
    landmarkType: "clockTower",
    primary: "#B31B1B",
    secondary: "#222222",
    highlight: "#D86161",
    texture: "ivy",
  },
  {
    id: "brown",
    name: "Brown University",
    shortName: "Brown",
    aliases: ["brown university", "brown"],
    city: "Providence",
    markText: "B",
    markStyle: "shield",
    landmark: "Van Wickle Gates",
    landmarkType: "gate",
    primary: "#4E3629",
    secondary: "#C00404",
    highlight: "#A07863",
    texture: "ivy",
  },
  {
    id: "dartmouth",
    name: "Dartmouth College",
    shortName: "Dartmouth",
    aliases: ["dartmouth college", "dartmouth"],
    city: "Hanover",
    markText: "D",
    markStyle: "serif",
    landmark: "Baker-Berry Library",
    landmarkType: "tower",
    primary: "#00693E",
    secondary: "#FFFFFF",
    highlight: "#47A67F",
    texture: "ivy",
  },
  {
    id: "mit",
    name: "Massachusetts Institute of Technology",
    shortName: "MIT",
    aliases: [
      "massachusetts institute of technology",
      "mit",
    ],
    city: "Cambridge",
    markText: "MIT",
    markStyle: "block",
    landmark: "The Great Dome",
    landmarkType: "dome",
    primary: "#A31F34",
    secondary: "#8A8B8C",
    highlight: "#D1586B",
    texture: "grid",
  },
  {
    id: "stanford",
    name: "Stanford University",
    shortName: "Stanford",
    aliases: ["stanford university", "stanford"],
    city: "Stanford",
    markText: "S",
    markStyle: "serif",
    landmark: "Hoover Tower",
    landmarkType: "tower",
    primary: "#8C1515",
    secondary: "#2E2D29",
    highlight: "#B83A4B",
    texture: "rays",
  },
  {
    id: "berkeley",
    name: "University of California, Berkeley",
    shortName: "Berkeley",
    aliases: [
      "university of california berkeley",
      "university of california, berkeley",
      "uc berkeley",
      "berkeley",
      "cal",
    ],
    city: "Berkeley",
    markText: "B",
    markStyle: "serif",
    landmark: "Sather Tower",
    landmarkType: "tower",
    primary: "#003262",
    secondary: "#FDB515",
    highlight: "#4D6F92",
    texture: "rays",
  },
  {
    id: "ucla",
    name: "University of California, Los Angeles",
    shortName: "UCLA",
    aliases: [
      "university of california los angeles",
      "university of california, los angeles",
      "ucla",
    ],
    city: "Los Angeles",
    markText: "UCLA",
    markStyle: "minimal",
    landmark: "Royce Hall",
    landmarkType: "hall",
    primary: "#2774AE",
    secondary: "#FFD100",
    highlight: "#6EA4CC",
    texture: "rays",
  },
  {
    id: "usc",
    name: "University of Southern California",
    shortName: "USC",
    aliases: [
      "university of southern california",
      "usc",
    ],
    city: "Los Angeles",
    markText: "SC",
    markStyle: "serif",
    landmark: "Tommy Trojan",
    landmarkType: "statue",
    primary: "#990000",
    secondary: "#FFCC00",
    highlight: "#D85555",
    texture: "rays",
  },
  {
    id: "duke",
    name: "Duke University",
    shortName: "Duke",
    aliases: ["duke university", "duke"],
    city: "Durham",
    markText: "D",
    markStyle: "serif",
    landmark: "Duke Chapel",
    landmarkType: "chapel",
    primary: "#012169",
    secondary: "#00539B",
    highlight: "#4F78B6",
    texture: "arches",
  },
  {
    id: "unc",
    name: "University of North Carolina at Chapel Hill",
    shortName: "UNC",
    aliases: [
      "university of north carolina at chapel hill",
      "unc chapel hill",
      "unc",
      "carolina",
    ],
    city: "Chapel Hill",
    markText: "NC",
    markStyle: "serif",
    landmark: "Old Well",
    landmarkType: "well",
    primary: "#7BAFD4",
    secondary: "#13294B",
    highlight: "#B8D8EC",
    texture: "arches",
  },
  {
    id: "georgia-tech",
    name: "Georgia Institute of Technology",
    shortName: "Georgia Tech",
    aliases: [
      "georgia institute of technology",
      "georgia tech",
      "gatech",
    ],
    city: "Atlanta",
    markText: "GT",
    markStyle: "block",
    landmark: "Tech Tower",
    landmarkType: "tower",
    primary: "#B3A369",
    secondary: "#003057",
    highlight: "#D9CEAA",
    texture: "grid",
  },
  {
    id: "texas",
    name: "The University of Texas at Austin",
    shortName: "Texas",
    aliases: [
      "the university of texas at austin",
      "university of texas at austin",
      "ut austin",
      "texas",
    ],
    city: "Austin",
    markText: "T",
    markStyle: "serif",
    landmark: "UT Tower",
    landmarkType: "tower",
    primary: "#BF5700",
    secondary: "#FFFFFF",
    highlight: "#E98A43",
    texture: "rays",
  },
  {
    id: "texas-am",
    name: "Texas A&M University",
    shortName: "Texas A&M",
    aliases: [
      "texas a&m university",
      "texas a&m",
      "tamu",
    ],
    city: "College Station",
    markText: "AM",
    markStyle: "block",
    landmark: "Century Tree",
    landmarkType: "tree",
    primary: "#500000",
    secondary: "#FFFFFF",
    highlight: "#8A4545",
    texture: "ivy",
  },
  {
    id: "florida",
    name: "University of Florida",
    shortName: "Florida",
    aliases: ["university of florida", "florida", "uf"],
    city: "Gainesville",
    markText: "F",
    markStyle: "block",
    landmark: "Century Tower",
    landmarkType: "tower",
    primary: "#0021A5",
    secondary: "#FA4616",
    highlight: "#5571D2",
    texture: "rays",
  },
  {
    id: "florida-state",
    name: "Florida State University",
    shortName: "Florida State",
    aliases: [
      "florida state university",
      "florida state",
      "fsu",
    ],
    city: "Tallahassee",
    markText: "FS",
    markStyle: "serif",
    landmark: "Westcott Building",
    landmarkType: "hall",
    primary: "#782F40",
    secondary: "#CEB888",
    highlight: "#A96575",
    texture: "arches",
  },
  {
    id: "alabama",
    name: "The University of Alabama",
    shortName: "Alabama",
    aliases: [
      "the university of alabama",
      "university of alabama",
      "alabama",
    ],
    city: "Tuscaloosa",
    markText: "A",
    markStyle: "serif",
    landmark: "Denny Chimes",
    landmarkType: "tower",
    primary: "#9E1B32",
    secondary: "#FFFFFF",
    highlight: "#D65B70",
    texture: "rays",
  },
  {
    id: "auburn",
    name: "Auburn University",
    shortName: "Auburn",
    aliases: ["auburn university", "auburn"],
    city: "Auburn",
    markText: "AU",
    markStyle: "serif",
    landmark: "Samford Hall",
    landmarkType: "clockTower",
    primary: "#0C2340",
    secondary: "#F26522",
    highlight: "#426482",
    texture: "grid",
  },
  {
    id: "tennessee",
    name: "University of Tennessee, Knoxville",
    shortName: "Tennessee",
    aliases: [
      "university of tennessee knoxville",
      "university of tennessee, knoxville",
      "tennessee",
      "utk",
    ],
    city: "Knoxville",
    markText: "T",
    markStyle: "block",
    landmark: "Ayres Hall",
    landmarkType: "clockTower",
    primary: "#FF8200",
    secondary: "#FFFFFF",
    highlight: "#FFB15E",
    texture: "rays",
  },
  {
    id: "georgia",
    name: "University of Georgia",
    shortName: "Georgia",
    aliases: ["university of georgia", "georgia", "uga"],
    city: "Athens",
    markText: "G",
    markStyle: "round",
    landmark: "The Arch",
    landmarkType: "arch",
    primary: "#BA0C2F",
    secondary: "#000000",
    highlight: "#E15C73",
    texture: "arches",
  },
  {
    id: "miami",
    name: "University of Miami",
    shortName: "Miami",
    aliases: ["university of miami", "miami"],
    city: "Coral Gables",
    markText: "U",
    markStyle: "minimal",
    landmark: "The U",
    landmarkType: "arch",
    primary: "#F47321",
    secondary: "#005030",
    highlight: "#FF9C62",
    texture: "rays",
  },
  {
    id: "nyu",
    name: "New York University",
    shortName: "NYU",
    aliases: ["new york university", "nyu"],
    city: "New York",
    markText: "NYU",
    markStyle: "minimal",
    landmark: "Washington Square Arch",
    landmarkType: "arch",
    primary: "#57068C",
    secondary: "#FFFFFF",
    highlight: "#8A4CB1",
    texture: "grid",
  },
  {
    id: "boston-college",
    name: "Boston College",
    shortName: "Boston College",
    aliases: ["boston college", "bc"],
    city: "Chestnut Hill",
    markText: "BC",
    markStyle: "serif",
    landmark: "Gasson Hall",
    landmarkType: "clockTower",
    primary: "#8A100B",
    secondary: "#BC9B6A",
    highlight: "#C45B56",
    texture: "ivy",
  },
  {
    id: "georgetown",
    name: "Georgetown University",
    shortName: "Georgetown",
    aliases: ["georgetown university", "georgetown"],
    city: "Washington, D.C.",
    markText: "G",
    markStyle: "serif",
    landmark: "Healy Hall",
    landmarkType: "hall",
    primary: "#041E42",
    secondary: "#63666A",
    highlight: "#49627F",
    texture: "ivy",
  },
  {
    id: "virginia",
    name: "University of Virginia",
    shortName: "Virginia",
    aliases: ["university of virginia", "virginia", "uva"],
    city: "Charlottesville",
    markText: "V",
    markStyle: "serif",
    landmark: "The Rotunda",
    landmarkType: "rotunda",
    primary: "#232D4B",
    secondary: "#E57200",
    highlight: "#59617A",
    texture: "arches",
  },
  {
    id: "virginia-tech",
    name: "Virginia Tech",
    shortName: "Virginia Tech",
    aliases: [
      "virginia polytechnic institute and state university",
      "virginia tech",
      "vt",
    ],
    city: "Blacksburg",
    markText: "VT",
    markStyle: "block",
    landmark: "Burruss Hall",
    landmarkType: "hall",
    primary: "#861F41",
    secondary: "#E87722",
    highlight: "#B45D78",
    texture: "grid",
  },
  {
    id: "maryland",
    name: "University of Maryland, College Park",
    shortName: "Maryland",
    aliases: [
      "university of maryland college park",
      "university of maryland, college park",
      "maryland",
      "umd",
    ],
    city: "College Park",
    markText: "M",
    markStyle: "block",
    landmark: "Testudo",
    landmarkType: "statue",
    primary: "#E03A3E",
    secondary: "#FFD520",
    highlight: "#F17B7E",
    texture: "grid",
  },
  {
    id: "minnesota",
    name: "University of Minnesota Twin Cities",
    shortName: "Minnesota",
    aliases: [
      "university of minnesota twin cities",
      "university of minnesota",
      "minnesota",
      "umn",
    ],
    city: "Minneapolis",
    markText: "M",
    markStyle: "serif",
    landmark: "Northrop",
    landmarkType: "library",
    primary: "#7A0019",
    secondary: "#FFCC33",
    highlight: "#A94D5F",
    texture: "grid",
  },
  {
    id: "washington",
    name: "University of Washington",
    shortName: "Washington",
    aliases: [
      "university of washington",
      "washington",
      "uw",
    ],
    city: "Seattle",
    markText: "W",
    markStyle: "serif",
    landmark: "Suzzallo Library",
    landmarkType: "library",
    primary: "#4B2E83",
    secondary: "#B7A57A",
    highlight: "#7964A1",
    texture: "ivy",
  },
  {
    id: "oregon",
    name: "University of Oregon",
    shortName: "Oregon",
    aliases: ["university of oregon", "oregon", "uo"],
    city: "Eugene",
    markText: "O",
    markStyle: "round",
    landmark: "Knight Library",
    landmarkType: "library",
    primary: "#154733",
    secondary: "#FEE123",
    highlight: "#4E7C69",
    texture: "rays",
  },
  {
    id: "colorado",
    name: "University of Colorado Boulder",
    shortName: "Colorado",
    aliases: [
      "university of colorado boulder",
      "university of colorado",
      "colorado",
      "cu boulder",
    ],
    city: "Boulder",
    markText: "CU",
    markStyle: "serif",
    landmark: "Old Main",
    landmarkType: "hall",
    primary: "#CFB87C",
    secondary: "#000000",
    highlight: "#E4D5AF",
    texture: "rays",
  },
  {
    id: "arizona",
    name: "University of Arizona",
    shortName: "Arizona",
    aliases: ["university of arizona", "arizona", "uarizona"],
    city: "Tucson",
    markText: "A",
    markStyle: "block",
    landmark: "Old Main",
    landmarkType: "hall",
    primary: "#CC0033",
    secondary: "#003366",
    highlight: "#E45B7B",
    texture: "rays",
  },
  {
    id: "arizona-state",
    name: "Arizona State University",
    shortName: "Arizona State",
    aliases: [
      "arizona state university",
      "arizona state",
      "asu",
    ],
    city: "Tempe",
    markText: "AS",
    markStyle: "serif",
    landmark: "Old Main",
    landmarkType: "hall",
    primary: "#8C1D40",
    secondary: "#FFC627",
    highlight: "#BA5F7B",
    texture: "rays",
  },
];

const fallback: SchoolIdentity = {
  id: "generic",
  name: "Your University",
  shortName: "University",
  aliases: [],
  city: "",
  markText: "U",
  markStyle: "serif",
  landmark: "Campus",
  landmarkType: "hall",
  primary: "#CFAE70",
  secondary: "#1C1C1C",
  highlight: "#F3DFB6",
  texture: "grid",
};

function normalize(value: string) {
  return value
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[^\p{L}\p{N}]+/gu, " ")
    .trim();
}

export function getSchoolIdentity(
  schoolName: string | null | undefined,
  databasePrimary?: string | null,
  databaseSecondary?: string | null,
): SchoolIdentity {
  const target = normalize(schoolName ?? "");

  if (!target) {
    return {
      ...fallback,
      primary: databasePrimary || fallback.primary,
      secondary: databaseSecondary || fallback.secondary,
      highlight: databasePrimary || fallback.highlight,
    };
  }

  const matched =
    identities.find((identity) =>
      identity.aliases.some((alias) => {
        const normalizedAlias = normalize(alias);

        return (
          target === normalizedAlias ||
          target.includes(normalizedAlias) ||
          normalizedAlias.includes(target)
        );
      }),
    ) ?? fallback;

  if (matched.id === "generic") {
    const cleanName = schoolName?.trim() || fallback.name;
    const words = cleanName
      .replace(/\buniversity\b/gi, "")
      .replace(/\bcollege\b/gi, "")
      .trim()
      .split(/\s+/)
      .filter(Boolean);

    const markText =
      words.length >= 2
        ? `${words[0]?.[0] ?? "U"}${words[1]?.[0] ?? ""}`.toUpperCase()
        : (words[0]?.[0] ?? "U").toUpperCase();

    return {
      ...fallback,
      name: cleanName,
      shortName: words.slice(0, 2).join(" ") || "University",
      markText,
      primary: databasePrimary || fallback.primary,
      secondary: databaseSecondary || fallback.secondary,
      highlight: databasePrimary || fallback.highlight,
    };
  }

  return {
    ...matched,
    primary: databasePrimary || matched.primary,
    secondary: databaseSecondary || matched.secondary,
  };
}

export function allCuratedSchoolIdentities() {
  return identities;
}